# workshop-template https://github.com/evanwill/workshop-template
# A Jekyll template for a simple workshop website, designed for github-pages,
# based on Minima theme https://github.com/jekyll/minima

# Notes:
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - pages with "nav: true" in front matter will be in header nav
# - use environment variable on build command to include analytics: JEKYLL_ENV=production jekyll build

# site settings
title: Sam Clark Tutoring
description: "A maths and physics tutor for you."
keywords: "github, github-pages, websites, static gen, hosting, html, workshop, gh-pages"

# author settings for cc-by
author: sam clark
pub_year: 2018
github_username: samclark1541

# add the full url for the github repository
repo: "https://github.com/samclark1541/GOGO"

# urls
# your gh-pages url: https://username.github.io
url: https://samclark1541.github.io
# your repository name: /repository
baseurl: /GOGO

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
